### ISSUE TITLE
`importwallet` doesn't work

### ISSUE THREAD

**Issue by randomlogin** [spacesprotocol/spaced#26]
Expected behaviour is that the output of `exportwallet` is understood by `importwallet`, however it's not the case: 
```
$ space-cli loadwallet default
$ space-cli exportwallet > a
$ space-cli importwallet a
{
  "code": -32602,
  "message": "Invalid params"
}
```

Example output of `exportwallet`: 
```
{"descriptor":"wpkh(tprv8ZgxMBicQKsPenCVzoWuz882YSb2AcuDVAyCNNTF9n6ffZUwMui3TRkHBTcavyuZ2mjA41Hyppboj2eSY26YaBEAmTysmH5H6yGXtocfHc1/84'/1'/0'/0/*)","spaces_descriptor":"tr(tprv8ZgxMBicQKsPenCVzoWuz882YSb2AcuDVAyCNNTF9n6ffZUwMui3TRkHBTcavyuZ2mjA41Hyppboj2eSY26YaBEAmTysmH5H6yGXtocfHc1/200'/86'/1'/0'/0/*)","blockheight":48585,"label":"default"}
```

Also json-rpc response is:

```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params",
        "data": "invalid type: map, expected a borrowed string at line 1 column 0"
    },
    "id": 1
}
```

Current workaround is to create a file in spaced wallets dir (on linux it's at `~/.local/share/spaced/testnet4/wallets/default/wallet.json`).

P.S. it's `importwallet` in CLI, but `walletimport` in JSON-RPC

**Comment by Ximik** [comment]
It seems like an issue in `jsonrpsee` itself.
It doesn't allow string params with `"` symbol in it. Escaping it with `\` or using `\u` sequence does not help either.
