### ISSUE TITLE
space-cli doesn't honor the -w option when multiple loaded wallets are available

### ISSUE THREAD

**Issue by andrewlunde** [spacesprotocol/spaced#7]
In my system I have a "default" wallet and a "phaedrus" wallet both were "loaded".  
Note: spaces is an alias for space-cli --chain testnet4

$ **spaces exportwallet**
{"descriptor":"wpkh(tprv8Z...o6zp/84'/1'/0'/0/*)","spaces_descriptor":"tr(tprv8Z...o6zp/200'/86'/1'/0'/0/*)","blockheight":41529,**"label":"default"**}

$ **spaces exportwallet -w phaedrus**
{"descriptor":"wpkh(tprv8Z...o6zp/84'/1'/0'/0/*)","spaces_descriptor":"tr(tprv8Z...o6zp/200'/86'/1'/0'/0/*)","blockheight":41529,**"label":"default"**}

This should have been the output below...

$ cat /data/wallets/phaedrus/wallet.json 
{"descriptor":"wpkh(tprv8Z...AFzf/84'/1'/0'/0/*)","spaces_descriptor":"tr(tprv8Z...AFzf/200'/86'/1'/0'/0/*)","blockheight":42839,**"label":"phaedrus"**}

**Comment by buffrr** [comment]
The exportwallet command expects the wallet name as an argument, e.g., `exportwallet <walletname>`. If no wallet name is specified, it defaults to exporting the `default` wallet. I can understand the confusion in thinking the -w option would work here.

I think it would be better for this command to take a `<path>` instead similar to bitcoin-cli e.g.

```
exportwallet -w walletname /path/to/export
```
