### ISSUE TITLE
Unclear when to specify @ in space name

### ISSUE THREAD

**Issue by andrewlunde** [spacesprotocol/spaced#8]
When attempting to send from one wallet to another where the target wallet own a space, docs are unclear that you need to preface space name with '@'.  Docs example have it correct.  https://docs.spacesprotocol.org/getting-started/resolver but spaces-cli send --help could be a bit clearer.

$ spaces send 5000 -f 3 --to **phaedrus**
{
  "code": -1,
  "message": "recipient must be a valid space name or an address"
}
$ spaces send 5000 -f 3 --to **@phaedrus**
{
  "sent": [
    {
      "txid": "f2a7663d9b00aa4e5ea0f67a04a5fd329c2f24154d93cc7162c3bfee29516a34",
      "tags": [
        "transfers"
      ]
    }
  ]
}

**Comment by buffrr** [comment]
agreed perhaps this should be "recipient must be a valid space name prefixed with @ or an address"
